firstProject/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views

from django.conf.urls import include

# urlpatterns = [
#     path('first_app/',include('first_app.urls')),
#     path('',views.index,name="index"),
#     path('formpage/',views.form_name_view,name='form_name'),
#     path('users/',views.users,name="users"),
#     path('admin/', admin.site.urls),
   
# ]

urlpatterns = [
    path('',views.index,name='index'),
    path('',include('first_app.urls')),
    path('admin/', admin.site.urls),
]

first_app/urls.py
from django.conf.urls import url
from first_app import views

app_name = 'first_app'

# urlpatterns = [
#     url('',views.index,name="index")
# ]

urlpatterns = [
    url('first/',views.first,name="first"),
    url('formpage/',views.form_name_view,name='form_name'),
    url('users/',views.users,name="users"),
]

first_app/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete=models.DO_NOTHING)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=254,unique=True)

    def __str__(self):
        return self.email


################################################## COMMENT THIS
# from django.contrib.auth.models import User

# # Create your models here.
# class UserProfileInfo(models.Model):

#     # Create relationship (don't inherit from User!)
#     user = models.OneToOneField(User,on_delete=models.DO_NOTHING)

#     # Add any additional attributes you want
#     portfolio_site = models.URLField(blank=True)
#     # pip install pillow to use this!
#     # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
#     profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

#     def __str__(self):
#         # Built-in attribute of django.contrib.auth.models.User !
#         return self.user.username

first_app/forms.py
from django import forms
from first_app.models import User
#django validator
from django.core import validators 

# def name_for_z(value):
#     if value[0].lower() != 'z':
#         raise forms.ValidationError("value sholud start with z")

class FormName(forms.Form):
    # name = forms.CharField(validators=[name_for_z])
    name = forms.CharField()
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)
    verify_email = forms.EmailField(label="Enter your email again")

    def clean(self):
        all_clean_data = super().clean()
        print(all_clean_data)
        email = all_clean_data['email']
        vemail = all_clean_data['verify_email']
        if email != vemail :
            raise forms.ValidationError("BOTH THE email should match")



class NewUserForm(forms.ModelForm):
    class Meta: 
        model = User
        fields = "__all__"



    # botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,
    # validators=[validators.MaxLengthValidator(0)])

    # custom validator
    # def clean_botcatcher(self):
    #     botcatcher  = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError("O you got caught darling")
    #     return botcatcher


##################################-- FOR USERINFOPROFILE --################################### COMMENT THIS

# from django.contrib.auth.models import User
# from first_app.models import UserProfileInfo

# class UserForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput())

#     class Meta():
#         model = User
#         fields = ('username','email','password')


# class UserProfileInfoForm(forms.ModelForm):
#     class Meta():
#         model = UserProfileInfo
#         fields = ('portfolio_site','profile_pic')

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic,Webpage,AccessRecord,User
from . import forms

# Create your views here.

def index(request) :
    # my_dict = {'text' : "oh yeah i am inserted"}
    web_list = AccessRecord.objects.order_by('date')

    web_dict = { 'text' : 'hello world','number' : 99 }

    return render(request,'first_app/index.html',context=web_dict) 

def first(request) :
    # my_dict = {'text' : "oh yeah i am inserted"}
    web_list = AccessRecord.objects.order_by('date')

    web_dict = { 'accessrecord' : web_list }

    return render(request,'first_app/first.html',context=web_dict) 

def form_name_view(request) :
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("Success!")
            print("Name: " + form.cleaned_data['name'])


    return render(request,'first_app/form_page.html',{'form': form})   

def users(request):
    form = forms.NewUserForm()

    if request.method == 'POST':
        form = forms.NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit = True)
            return index(request)    # it is like request.redirect
        else :
            print('Error')
 
    return render(request,'first_app/signup.html',{'form' : form})

templates/first_app/first.html
<!DOCTYPE html>


{% extends "first_app/index.html" %}
    {% block body_block %}

    {% load static %}
    <div class="djangoOne text-center">
        <h1 id="hid">
            OK i m join
        </h1>
        {{text}}
        <img src="{% static "images/download.jpg" %}" onclick="called()">
    </div>
    <div class="djangoTwo">
        <table>
            {% if accessrecord%}
            <tr>
                <th>Name</th>
                <th>Date</th>
            </tr>
            {% for acc in accessrecord %}
            <tr>
                <td>{{acc.name}}</td>
                <td>{{acc.date}}</td>
            </tr>
            {% endfor%}
            {% else %}
            <p>No record to access</p>
            {% endif %}
        </table>
    </div>


   {%  endblock %}
    

templates/first_app/form_page.html
<!DOCTYPE html>

{% extends "first_app/index.html" %}
    {% block body_block %}
        <h1>This is a form page</h1>
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="submit">
        </form>
    {%  endblock %}

templates/first_app/index.html
<!DOCTYPE html>
{% load static %}

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Index Page</title>
    <link rel="stylesheet" href="{% static "css/mystyle.css"  %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-fixed-top">
        <a href="#" class="navbar-brand">
            Movie DB
        </a>
        <!-- hamburger wala -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'first_app:first'  %}">First</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'first_app:form_name'  %}">Form Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'first_app:users'  %}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index'  %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index'  %}">Index</a>
                </li>
            </ul>
        </div>
    </nav>


    <h1>This is the index page</h1>
    {{text|cut:'wo'|upper}}
    </br>
    {{number|add:'99'}}
    <div class="container">
        {% block body_block%}
        <!-- Anything outside of this will be inherited if you extend -->
        {% endblock %}
    </div>




    <!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
</script>


</body>

</html>

templates/first_app/signup.html
<!DOCTYPE html>

{% extends "first_app/index.html" %}
    {% block body_block %}


        <h1>Please signup here</h1>
        <form  method="POST">
            {{ form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value='submit'>
        </form>

        
    {%  endblock %}